export const AUTH_USER = 'AUTH_USER'
export const USER_REQUEST = 'USER_REQUEST'
export const USER_SUCCESS = 'USER_SUCCESS'
export const USER_TYPES = 'USER_TYPES'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const REFRESH_USER = 'REFRESH_USER'
export const USER_ERROR = 'USER_ERROR'
