export const SIGN_IN = 'SIGN_IN'
export const SIGN_UP = 'SIGN_UP'
export const AUTH_REQUEST = 'AUTH_REQUEST'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const AUTH_USER = 'AUTH_USER'
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS'
export const USER_TYPES = 'USER_TYPES'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'
export const REFRESH_AUTH = 'REFRESH_AUTH'
export const USER_ERROR = 'USER_ERROR'
